### ISSUE TITLE
Exporting?

### ISSUE THREAD

**Issue by IdrisQe** [crunchyintheory/PoE-Item-Creator#3]
I might be misunderstanding how it's ment to work, but there's meant to be an import/export to JSON function in the site, right?
I've never been able to find it though- there's no button or anything. Right clicking anywhere does nothing except in the stash where it gives you the option to delete an item, so... How are you supposed to export? (And Import but that's less of a concern to me)

Also, if it's not too much work, could you add an export-to-image functionality? The size of some items makes it so I need to zoom out my browser to get the entire thing in one screenshot or snip, which then resizes the item tooltip and messes up the proportions compared to what's displayed ingame or on the wiki.

**Comment by crunchyintheory** [comment]
Unfortunately exporting to image is relatively difficult while preserving the formatting. I had a feature like this in a previous version of the app, and it never worked properly with the embedded images and fonts. 

If you could add a screenshot of the sizing issues you're experiencing, I can try to address those.

**Comment by IdrisQe** [comment]
This is what I mean. When I zoom out to screenshot an item, the size of the "bounding box" expands, which causes tooltips to be inconsistently wide. I know that tooltips in PoE can expand horizontally, but there's a limit to it in PoE to avoid them from getting absurdly wide. It would be nice to have a way to limit the width (though that might be difficult since it's probably my browser's zoom functionality causing the problem, and every browser has a different zoom implementation for some ungodly reason)
![gif](https://github.com/crunchyintheory/PoE-Item-Creator/assets/40530630/744f8b28-e76a-48d8-9ed4-28a20de3bc5d)

**Comment by crunchyintheory** [comment]
Let me know if this doesn't solve your issue, it's building right now and should be live shortly. If the text input for selecting a maximum width doesn't appear, try hard reloading your browser (Ctrl + R in Firefox)
